# Generated by Django 2.2 on 2019-10-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='Image',
        ),
    ]
